add license
OccamX-MilkomedaDEX/Milkomeda-OCCAMX-sc pull request #8
Opened 2022-09-06 03:25 UTC by anhdungle93

- follow instructions of dependebot to solve prototype pollution security issues
- add GPL3 license

2022-09-06 07:43 UTC, zwilling requested changes
Can you please remove the `.DS_Store` file?
Otherwise I am wondering about the SPDX statements in our contracts. Shouldn't they also have the same License?

2022-09-06 07:43 UTC, zwilling commented on flattened/ProtocolTokenMintable.sol
> +// SPDX-License-Identifier: UNLICENSED
Shouldn't this then also be GPL3?

2022-09-06 10:49 UTC, anhdungle93 commented on flattened/ProtocolTokenMintable.sol
> +// SPDX-License-Identifier: UNLICENSED
I removed it from ProtocolToken, because there are also other contracts without specified LICENSE/UNLICENSED, so I guess they inherit GPL3. There are still some contracts we took from elsewhere, like ZapOccamX, this one is GPL2 so there is no conflict with GPL3. Ownable has MIT, so it has to stay MIT, I am not sure how to resolve this. Do you know?

2022-09-06 15:47 UTC, zwilling commented on flattened/ProtocolTokenMintable.sol
> +// SPDX-License-Identifier: UNLICENSED
Can they just keep their license? I think it is ok to have different licenses in the different parts used.

2022-09-08 14:35 UTC, zwilling approved these changes
I think it can be merged now

2022-09-08 14:35 UTC, merged